# config.py - placeholders
MODE = 'DEV'  # 'DEV' or 'PROD'

# Database
DB_HOST = 'YOUR_DB_HOST'
DB_USER = 'YOUR_DB_USER'
DB_PASSWORD = 'YOUR_DB_PASSWORD'
DB_NAME = 'YOUR_DB_NAME'

# OpenAI
OPENAI_API_KEY = 'YOUR_OPENAI_API_KEY'

# Email
EMAIL_ADDRESS = 'YOUR_EMAIL_ADDRESS'
EMAIL_PASSWORD = 'YOUR_EMAIL_PASSWORD'
RECIPIENT_EMAIL = 'CLIENT_EMAIL_ADDRESS'
